### ISSUE TITLE
Documentation or instructions to integrate it with quill

### ISSUE THREAD

**Issue by kiran-zotalabs** [JonathanTreffler/Quill-mathLive-blot#6]
Can I get the Documentation or a set of instructions  so that I can use this library to integrate it with Quill 

Thank you,
Kiran

**Comment by JonathanTreffler** [comment]
I will update the README to be more specific

**Comment by JonathanTreffler** [comment]
I am currently building a demo site. It will be ready today or tomorrow

**Comment by JonathanTreffler** [comment]
@kiran-zotalabs The demo works now: https://jonathan-treffler.de/Quill-mathLive-blot/
But i will improve it tomorrow. Then i will add it to the README.

**Comment by JonathanTreffler** [comment]
I will close this now :)
